In [21]:
import mysql.connector
import pandas as pd
import re
import tkinter as tk
from tkinter import messagebox

### Create database connection
def create_db_connection():
    connection = None
    try:
        connection = mysql.connector.connect(
            host='localhost',
            user='root',
            passwd='catrat123',
            database='restaurant_delivery'
        )
        print("MySQL Database connection successful")
    except mysql.connector.Error as err:
        print(f"Error: '{err}'")
    return connection

db_connection = create_db_connection()



    
#clean data
def clean_data(df):
    df = df.fillna('n/a')
    return df

restaurant_df = pd.read_csv("restaurant_info.csv")
restaurant_df = clean_data(restaurant_df)

orders_df = pd.read_csv("orders.csv")
orders_df = clean_data(orders_df)

###Data Cleaning process

#Drop the 'Store' column from the 'restaurants' data frame
restaurant_df.drop(columns=['Store'], inplace=True)


# replace missing values
restaurant_df.fillna({'Years_as_manager': 0, 'Email': 'unknown'}, inplace=True)


# missing values in the 'Delivery_Time_Taken_mins' column of orders_df will be filled with the mean value of that column
orders_df.fillna({'Delivery_Time_Taken_mins': orders_df['Delivery_Time_Taken_mins'].mean()}, inplace=True)



#'Years_as_manager' column in the restaurant_df DataFrame will contain integer values, and any non-numeric or missing values will be replaced with 0.
restaurant_df['Years_as_manager'] = pd.to_numeric(restaurant_df['Years_as_manager'], errors='coerce').fillna(0).astype(int)


# Clean data and validate email format
def is_valid_email(email):
    # Define a regular expression pattern to validate the email format
    pattern = r'^[a-zA-Z]+@[a-zA-Z]+\.[a-zA-Z]+$'
    return re.match(pattern, email) is not None

# Function to clean the 'Email' column in restaurant_df
def clean_email(email):
    if is_valid_email(email):
        return email
    else:
        return 'Invalid Email'

restaurant_df['Email'] = restaurant_df['Email'].apply(clean_email)



#Clean credit card and Debit card columns
orders_df['Credit_Card'] = orders_df['Credit_Card'].astype(str).str.replace(r'\D', '', regex=True)
orders_df['Debit_Card'] = orders_df['Debit_Card'].astype(str).str.replace(r'\D', '', regex=True)


#clean unnessary values from Delivery time taken column
#orders_df['Delivery_Time_Taken_mins'] = orders_df['Delivery_Time_Taken_mins'].str.extract('(\d+)').astype(int)




### Insert data into the 'restaurants' table


# Function to insert data into the 'restaurants' table with automatic generation of unique 'RestaurantID' values
# Function to insert data into the 'restaurants' table with automatic generation of unique 'RestaurantID' values
def insert_restaurant_data(connection, df):
    cursor = connection.cursor()
    
    for row in df[['RestaurantName', 'Cuisine', 'Zone', 'Category', 'Address']].itertuples(index=False, name=None):
        # Check if the data already exists in the 'restaurants' table based on the restaurant's attributes
        cursor.execute(
            "SELECT 1 FROM restaurants WHERE RestaurantName = %s AND Cuisine = %s AND Zone = %s AND Category = %s AND Address = %s",
            (row[0], row[1], row[2], row[3], row[4])
        )
        
        # Fetch the result of the SELECT query
        existing_data = cursor.fetchone()

        if not existing_data:
            # Insert the data into the 'restaurants' table with an automatically generated unique 'RestaurantID'
            cursor.execute(
                "INSERT INTO restaurants (RestaurantName, Cuisine, Zone, Category, Address) VALUES (%s, %s, %s, %s, %s)",
                (row[0], row[1], row[2], row[3], row[4])
            )
    
    connection.commit()
    cursor.close()




# Insert data into the 'orders' table
# Function to insert data into the 'orders' table with 'Order_ID' as a string
def insert_orders_data(connection, df):
    cursor = connection.cursor()
    
    for row in df[['Order_ID', 'RestaurantID', 'Order_Date', 'Quantity_of_Items', 'Order_Amount', 'First_Customer_Name', 'Last_Customer_Name','Customer_Rating_Food']].itertuples(index=False, name=None):
        cursor.execute("""
        INSERT INTO orders (OrderID, RestaurantID, OrderDate, QuantityofItems, OrderAmount, First_Customer_Name, Last_Customer_Name,Customer_Rating_Food)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
        ON DUPLICATE KEY UPDATE
        OrderID = VALUES(OrderID),
        RestaurantID = VALUES(RestaurantID),
        OrderDate = VALUES(OrderDate),
        QuantityofItems = VALUES(QuantityofItems),
        OrderAmount = VALUES(OrderAmount),
        First_Customer_Name = VALUES(First_Customer_Name),
        Last_Customer_Name = VALUES(Last_Customer_Name),
        Customer_Rating_Food = VALUES(Customer_Rating_Food)
    """, row)
    
    connection.commit()
    cursor.close()



# Insert data into the 'delivery' table while ensuring data uniqueness
def insert_delivery_data(connection, df):
    cursor = connection.cursor()
    for row in df[['Delivery_Time_Taken_mins', 'Customer_Rating_Food', 'Customer_Rating_Delivery', 'Order_ID']].itertuples(index=False, name=None):
        # Check if the data already exists in the 'delivery' table
        cursor.execute(
            "SELECT 1 FROM delivery WHERE DeliveryTimeTaken = %s AND Customer_Rating_Food = %s AND Customer_Rating_Delivery = %s AND OrderID = %s",
            (row[0], row[1], row[2], row[3])
        )
        
        # Fetch the result of the SELECT query
        existing_data = cursor.fetchone()

        # If the data doesn't exist, insert it
        if not existing_data:
            cursor.execute(
                "INSERT INTO delivery (DeliveryTimeTaken, Customer_Rating_Food, Customer_Rating_Delivery, OrderID) VALUES (%s, %s, %s, %s)",
                (row[0], row[1], row[2], row[3])
            )
    
    connection.commit()
    cursor.close()


# Insert data into the 'payments' table while ensuring data uniqueness
def insert_payments_data(connection, df):
    cursor = connection.cursor()
    for row in df[['Order_ID', 'Payment_Mode']].itertuples(index=False, name=None):
        # Check if the data already exists in the 'payments' table
        cursor.execute(
            "SELECT 1 FROM payments WHERE OrderID = %s AND Payment_Mode = %s",
            (row[0], row[1])
        )
        
        # Fetch the result of the SELECT query
        existing_data = cursor.fetchone()

        # If the data doesn't exist, insert it
        if not existing_data:
            cursor.execute(
                "INSERT INTO payments (OrderID, Payment_Mode) VALUES (%s, %s)",
                (row[0], row[1])
            )
    
    connection.commit()
    cursor.close()


    
# Insert data into the 'cards' table while ensuring data uniqueness
def insert_cards_data(connection, orders_df):
    cursor = connection.cursor()
    for row in orders_df[['Card_Provider', 'Debit_Card', 'Credit_Card']].itertuples(index=False, name=None):
        # Check if the data already exists in the 'cards' table
        cursor.execute(
            "SELECT 1 FROM cards WHERE CardProvider = %s AND DebitCard = %s AND CreditCard = %s",
            (row[0], row[1], row[2])
        )
        
        # Fetch the result of the SELECT query
        existing_data = cursor.fetchone()

        # If the data doesn't exist, insert it
        if not existing_data:
            cursor.execute(
                "INSERT INTO cards(CardProvider, DebitCard, CreditCard) VALUES (%s, %s, %s)",
                (row[0], row[1], row[2])
            )
    
    connection.commit()
    cursor.close()

# Insert data into the 'manager' table while ensuring data uniqueness
def insert_manager_data(connection, df):
    cursor = connection.cursor()
    for row in df[['RestaurantID', 'Manager', 'Years_as_manager', 'Email']].itertuples(index=False, name=None):
        # Check if the data already exists in the 'manager' table
        cursor.execute(
            "SELECT 1 FROM manager WHERE RestaurantID = %s AND Manager = %s AND Years_as_manager = %s AND Email = %s",
            (row[0], row[1], row[2], row[3])
        )
        
        # Fetch the result of the SELECT query
        existing_data = cursor.fetchone()

        # If the data doesn't exist, insert it
        if not existing_data:
            cursor.execute(
                "INSERT INTO manager (RestaurantID, Manager, Years_as_manager, Email) VALUES (%s, %s, %s, %s)",
                (row[0], row[1], row[2], row[3])
            )
    
    connection.commit()
    cursor.close()



# Insert data into the relevant tables
insert_restaurant_data(db_connection, restaurant_df)
insert_orders_data(db_connection, orders_df)
insert_delivery_data(db_connection, orders_df)
insert_payments_data(db_connection, orders_df)
insert_cards_data(db_connection, orders_df)
insert_manager_data(db_connection, restaurant_df)

# Close the database connection
db_connection.close()

MySQL Database connection successful

In [21]:
import mysql.connector
import pandas as pd
import re
import tkinter as tk
from tkinter import messagebox


def create_db_connection():
    connection = None
    try:
        connection = mysql.connector.connect(
            host='localhost',
            user='root',
            passwd='catrat123',
            database='restaurant_delivery'
        )
        print("MySQL Database connection successful")
    except mysql.connector.Error as err:
        print(f"Error: '{err}'")
    return connection

db_connection = create_db_connection()

# Define the function to update the manager
def update_manager():
    # Get values from the GUI input fields
    restaurant_id = restaurant_id_entry.get()
    new_manager = new_manager_entry.get()
    new_email = new_email_entry.get()

    # Validate email format
    if not is_valid_email(new_email):
        messagebox.showerror("Invalid Email", "Please enter a valid email address Ex:(name@gmail.com).")
        return

    # Update the manager in the database
    try:
        cursor = db_connection.cursor()
        cursor.execute("UPDATE manager SET Manager = %s, Email = %s WHERE RestaurantID = %s", (new_manager, new_email, restaurant_id))
        db_connection.commit()
        cursor.close()
        messagebox.showinfo("Success", "Manager information updated successfully.")
    except mysql.connector.Error as err:
        messagebox.showerror("Database Error", f"Error: {err}")

# Create a Tkinter window
root = tk.Tk()
root.title("Update Manager")

# Create a title label
title_label = tk.Label(root, text="Update Restaurant Manager", font=("Helvetica", 16))
title_label.grid(row=0, column=0, columnspan=2, pady=10)

# Create a frame for input fields
input_frame = tk.Frame(root)
input_frame.grid(row=1, column=0, columnspan=2, padx=10, pady=5)

# Create labels and entry fields for restaurant ID, new manager, and new email
restaurant_id_label = tk.Label(input_frame, text="Restaurant ID:")
restaurant_id_label.grid(row=0, column=0, padx=5, pady=5)
restaurant_id_entry = tk.Entry(input_frame)
restaurant_id_entry.grid(row=0, column=1, padx=5, pady=5)

new_manager_label = tk.Label(input_frame, text="New Manager:")
new_manager_label.grid(row=1, column=0, padx=5, pady=5)
new_manager_entry = tk.Entry(input_frame)
new_manager_entry.grid(row=1, column=1, padx=5, pady=5)

new_email_label = tk.Label(input_frame, text="New Email:")
new_email_label.grid(row=2, column=0, padx=5, pady=5)
new_email_entry = tk.Entry(input_frame)
new_email_entry.grid(row=2, column=1, padx=5, pady=5)

# Create a button to update the manager
update_button = tk.Button(root, text="Update Manager", command=update_manager, bg="green", fg="white", font=("Helvetica", 12))
update_button.grid(row=2, column=0, columnspan=2, pady=10)

# Create a function to validate email format
def is_valid_email(email):
    pattern = r'^[a-zA-Z]+@[a-zA-Z]+\.[a-zA-Z]+$'
    return re.match(pattern, email) is not None

# Initialize the database connection (you can include this part from your existing code)
# db_connection = create_db_connection()

# Run the Tkinter main loop
root.mainloop()

# Close the database connection (you can include this part from your existing code)
# db_connection.close()

MySQL Database connection successful

In [18]:
import mysql.connector
import tkinter as tk
from tkinter import ttk, messagebox
import matplotlib.pyplot as plt
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from tkinter import Toplevel

# Create a database connection (you can include this part from your existing code)
def create_db_connection():
    connection = None
    try:
        connection = mysql.connector.connect(
            host='localhost',
            user='root',
            passwd='catrat123',
            database='restaurant_delivery'
        )
        print("MySQL Database connection successful")
    except mysql.connector.Error as err:
        print(f"Error: '{err}'")
    return connection

db_connection = create_db_connection()

# Fetch and display restaurant ratings in a tabular format
def display_mean_ratings():
    try:
        cursor = db_connection.cursor()
        cursor.execute("SELECT restaurants.RestaurantName, AVG(orders.Customer_Rating_Food) "
                       "FROM orders "
                       "INNER JOIN restaurants ON orders.RestaurantID = restaurants.RestaurantID "
                       "GROUP BY restaurants.RestaurantName")
        result = cursor.fetchall()
        cursor.close()

        # Create a new top-level window for mean ratings
        top = tk.Toplevel()
        top.title("Mean Ratings")

        # Create a Treeview widget to display ratings
        tree = ttk.Treeview(top, columns=("Restaurant", "Mean Rating"), show="headings")
        tree.heading("Restaurant", text="Restaurant")
        tree.heading("Mean Rating", text="Mean Rating")

        # Add ratings data to the Treeview
        for row in result:
            tree.insert("", "end", values=(row[0], f"{row[1]:.2f}"))

        # Create a scrollbar for the Treeview
        scrollbar = ttk.Scrollbar(top, orient="vertical", command=tree.yview)
        tree.configure(yscrollcommand=scrollbar.set)

        # Pack the Treeview and scrollbar
        tree.pack(fill="both", expand=True)
        scrollbar.pack(side="right", fill="y")

    except mysql.connector.Error as err:
        messagebox.showerror("Database Error", f"Error: {err}")

# Create the main analysis window
analysis_window = tk.Tk()
analysis_window.title("Data Analysis")
analysis_window.geometry("300x200")

# Create labels and buttons to perform analysis tasks
ratings_label = tk.Label(analysis_window, text="Calculate Mean of the coustomer\n ratings for foods", font=("Helvetica", 12))
ratings_label.pack(pady=10)
ratings_button = tk.Button(analysis_window, text="Calculate", command=display_mean_ratings, bg="green", fg="white")
ratings_button.pack()

# Fetch delivery time data from the 'delivery' table
def fetch_delivery_data():
    try:
        cursor = db_connection.cursor()
        cursor.execute("SELECT DeliveryTimeTaken FROM delivery")
        delivery_times = [row[0] for row in cursor.fetchall() if row[0] is not None and row[0] >= 0]
        cursor.close()
        return delivery_times
    except mysql.connector.Error as err:
        messagebox.showerror("Database Error", f"Error: {err}")
        return []

# Create a bar plot for delivery time intervals
def create_delivery_time_bar_plot():
    delivery_times = fetch_delivery_data()

    if not delivery_times:
        messagebox.showinfo("No Data", "No data to display in the bar chart.")
        return

    # Create bins for delivery time intervals with a width of 2 minutes
    bins = list(range(5, 50, 2)) 

    # Create a new top-level window for the bar chart
    bar_chart_window = Toplevel(analysis_window)
    bar_chart_window.title("Delivery Time Taken Bar Chart")

    # Create a figure for the bar chart
    figure = plt.Figure(figsize=(8, 6), dpi=90)
    ax = figure.add_subplot(111)

    # Create the bar chart
    ax.hist(delivery_times, bins=bins, color='skyblue', edgecolor='black')
    ax.set_xlabel("Delivery Time Taken (mins)")
    ax.set_ylabel("Number of Deliveries")
    ax.set_title("Delivery Time Taken Distribution")

    # Create the canvas and add it to the bar chart window
    canvas = FigureCanvasTkAgg(figure, master=bar_chart_window)
    canvas.get_tk_widget().pack()
    canvas.draw()

bar_chart_label = tk.Label(analysis_window, text="Draw Delivery Time Bar Chart", font=("Helvetica", 12))
bar_chart_label.pack(pady=10)

# Create a button to draw the delivery time bar plot
bar_chart_button = tk.Button(analysis_window, text="Draw Delivery Time Bar Chart", command=create_delivery_time_bar_plot, bg="blue", fg="white")
bar_chart_button.pack(pady=10)

# Run the Tkinter main loop
analysis_window.mainloop()

# Close the database connection (you can include this part from your existing code)
db_connection.close()

MySQL Database connection successful